package code.inspector.core;

public interface Const {
    // DOS
    String DOS_MODULE = "DOS_MODULE";
    String DOS_FOR_TYPE = "DOS_FOR_TYPE";
    String DOS_ARRAY_TYPE = "DOS_ARRAY_TYPE";
    String DOS_LIST_TYPE = "DOS_LIST_TYPE";
    String DOS_REGEX_TYPE = "DOS_REGEX_TYPE";
    // RCE
    String RCE_MODULE = "RCE_MODULE";
    String RCE_RUNTIME_TYPE = "RCE_RUNTIME_TYPE";
    String RCE_PROCESS_TYPE = "RCE_PROCESS_TYPE";
    String RCE_GROOVY_TYPE = "RCE_GROOVY_TYPE";
    String RCE_JNDI_TYPE = "RCE_JNDI_TYPE";
    String RCE_SP_EL_TYPE = "RCE_SP_EL_TYPE";
    // Redirect
    String REDIRECT_MODULE = "REDIRECT_MODULE";
    String REDIRECT_STRING_TYPE = "REDIRECT_STRING_TYPE";
    String REDIRECT_SEND_RESPONSE_TYPE = "REDIRECT_SEND_RESPONSE_TYPE";
    String REDIRECT_MODEL_AND_VIEW_TYPE = "REDIRECT_MODEL_AND_VIEW_TYPE";
    // SQL Injection
    String SQL_MODULE = "SQL_MODULE";
    String SQL_JDBC_TEMPLATE_UPDATE = "SQL_JDBC_TEMPLATE_UPDATE";
    String SQL_JDBC_TEMPLATE_EXECUTE = "SQL_JDBC_TEMPLATE_EXECUTE";
    String SQL_JDBC_TEMPLATE_QUERY_ANY = "SQL_JDBC_TEMPLATE_QUERY_ANY";
    String SQL_EXECUTE_UPDATE = "SQL_EXECUTE_UPDATE";
    String SQL_EXECUTE_QUERY = "SQL_EXECUTE_QUERY";
    String SQL_EXECUTE = "SQL_EXECUTE";
    // SSRF
    String SSRF_MODULE = "SSRF_MODULE";
    String SSRF_JDK_TYPE = "SSRF_JDK_TYPE";
    String SSRF_APACHE_TYPE = "SSRF_APACHE_TYPE";
    String SSRF_OKHTTP_TYPE = "SSRF_OKHTTP_TYPE";
    String SSRF_SOCKET_TYPE = "SSRF_SOCKET_TYPE";
    // Deserialization
    String DESERIALIZATION_MODULE = "DESERIALIZATION_MODULE";
    String DESERIALIZATION_JDK = "DESERIALIZATION_JDK";
    String DESERIALIZATION_FASTJSON = "DESERIALIZATION_FASTJSON";
    String DESERIALIZATION_JACKSON = "DESERIALIZATION_JACKSON";
    String DESERIALIZATION_SNAKEYAML = "DESERIALIZATION_SNAKEYAML";
    String DESERIALIZATION_HESSIAN = "DESERIALIZATION_HESSIAN";
    String DESERIALIZATION_XML_DECODER = "DESERIALIZATION_XML_DECODER";
}
